type User {
  id: ID!
  username: String!
  email: String!
  avatar: String
  notes: [Note!]!
  favorites: [Note!]!
}

type Mutation {
  signUp(username: String!, email: String!, password: String!): String!
  signIn(username: String, email: String, password: String!): String!
  toggleFavorite(id: ID!): Note!
}
